CREATE TABLE [dbo].[GRUPOS]
(
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
    [GRUPO] NCHAR(50) NOT NULL, 
    [DESCRICAO] NCHAR(250) NOT NULL, 
    [NIVEL] INT NOT NULL , 
    [ESTATUS] NCHAR(1) NOT NULL 
)
