CREATE TABLE [dbo].[USUARIOS]
(
	[Id] INT NOT NULL IDENTITY(1,1)  PRIMARY KEY, 
    [USUARIO] VARCHAR(30) NOT NULL, 
    [SENHA] VARCHAR(30) NOT NULL, 
    [NOME] VARCHAR(100) NOT NULL, 
    [ID_GRUPO] INT NOT NULL, 
    [ESTATUS] NCHAR(1) NOT NULL  
)
